export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";

export const USER_LOAD_REQUEST = "USER_LOAD_REQUEST";
export const USER_LOAD_SUCCESS = "USER_LOAD_SUCCESS";
export const USER_LOAD_FAIL = "USER_LOAD_FAIL";

export const USER_CATEGORY_REQUEST = "USER_CATEGORY_REQUEST";
export const USER_CATEGORY_SUCCESS = "USER_CATEGORY_SUCCESS";
export const USER_CATEGORY_FAIL = "USER_CATEGORY_FAIL";


export const PRODUCTS_BY_CATEGORY_REQUEST = "PRODUCTS_BY_CATEGORY_REQUEST";
export const PRODUCTS_BY_CATEGORY_SUCCESS = "PRODUCTS_BY_CATEGORY_SUCCESS";
export const PRODUCTS_BY_CATEGORY_FAIL = "PRODUCTS_BY_CATEGORY_FAIL";


export const SET_SELECTED_PRODUCT = "SET_SELECTED_PRODUCT";
export const ADD_TO_CART = "ADD_TO_CART";

export const ADD_TO_WATCHLIST = 'ADD_TO_WATCHLIST';
export const REMOVE_FROM_WATCHLIST = 'REMOVE_FROM_WATCHLIST';

export const UPDATE_WATCHLIST_QUANTITY = "UPDATE_WATCHLIST_QUANTITY";
export const UPDATE_TOTAL_AMOUNT = "UPDATE_TOTAL_AMOUNT";


export const FETCH_RANDOM_PRODUCTS_REQUEST = "FETCH_RANDOM_PRODUCTS_REQUEST";
export const FETCH_RANDOM_PRODUCTS_SUCCESS = "FETCH_RANDOM_PRODUCTS_SUCCESS";
export const FETCH_RANDOM_PRODUCTS_FAIL = "FETCH_RANDOM_PRODUCTS_FAIL";

export const CHAT_MESSAGE_RECEIVED = "CHAT_MESSAGE_RECEIVED";
export const CHAT_MESSAGE_SENT = "CHAT_MESSAGE_SENT";
export const CHAT_CLEAR = "CHAT_CLEAR";

export const ADD_ADDRESS_REQUEST = "ADD_ADDRESS_REQUEST";
export const ADD_ADDRESS_SUCCESS = "ADD_ADDRESS_SUCCESS";
export const ADD_ADDRESS_FAIL = "ADD_ADDRESS_FAIL";

export const FETCH_ADDRESSES_REQUEST = "FETCH_ADDRESSES_REQUEST";
export const FETCH_ADDRESSES_SUCCESS = "FETCH_ADDRESSES_SUCCESS";
export const FETCH_ADDRESSES_FAIL = "FETCH_ADDRESSES_FAIL";


export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

export const VERIFY_PAYMENT_REQUEST = "VERIFY_PAYMENT_REQUEST";
export const VERIFY_PAYMENT_SUCCESS = "VERIFY_PAYMENT_SUCCESS";
export const VERIFY_PAYMENT_FAIL = "VERIFY_PAYMENT_FAIL";



